name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_token:
    description: 'github token'
    required: true
  model_name: 
    description: 'OpenAI model name'
    default: 'gpt-3.5-turbo'
  model_temperature:
    description: 'OpenAI model temperature'
    default: '0'
  exclude_files:
    description: "Provide a wildcard expression to exclude files from code review. For example, `*.md` will exclude all markdown files."
    required: false
    default: ""

runs:
  using: 'node16'
  main: 'dist/index.js'
